"
I store metadata for the OpenPonk-XMI-Inspection package. This package provides Pharo Inspector extensions and custom presentations to facilitate the exploration, debugging, and visualization of parsed XMI document structures and information items.
"
Class {
	#name : 'ManifestOpenPonkXMIInspection',
	#superclass : 'PackageManifest',
	#category : 'OpenPonk-XMI-Inspection-Manifest',
	#package : 'OpenPonk-XMI-Inspection',
	#tag : 'Manifest'
}
